Sprint 22 - part 1 Посмотрите описание
klyakssa/PlaylistNew pull request #28
Opened 2024-02-24 06:38 UTC by klyakssa

(Прошу! Как можно подробнее расскажите куда капать что бы исправить недочеты) Спасибо!)

2024-02-25 08:00 UTC, DmitrijEgorow requested changes

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/build.gradle
> +    implementation 'com.github.tbruyelle:rxpermissions:0.12'
Может, обойтись без rxpermissions?
Стоит унифицировать: здесь скобочек нет

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/data/db/converters/PlaylistDbConverter.kt
> +        return PlaylistEntity(0,playlistName,playlistDescribe,imgFilePath,"",0)
Перед коммитом стоит приводить файлы к правильному стилю, так как код будут смотреть другие разработчики. В студии это легко делать путём вызова горячей комбинации клавиш (она зависит от ОС), её можно посмотреть в меню Code → Reformat Code

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/data/db/entity/PlaylistEntity.kt
> +    val idAddedTracks: String,
Треки, добавляемые в плейлист, должны сохраняться в отдельную таблицу базы данных, а в этой таблице будет foreign key на другую таблицу

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/data/db/entity/PlaylistEntity.kt
> +    val imgFilePath: String,
content://media/picker/0/com.android.providers.media.photopicker/media/1000002953
не является путём к скопированному файлу
[Это Uri, предоставленный Content Provider](
https://developer.android.com/reference/android/content/ContentUris)

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/di/ViewModelModule.kt
> +        PlaylistViewModel(get())
Почему single, а не viewModel<>{} ?

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/domain/db/impl/FavoriteIteratorImpl.kt
> +class FavoriteIteratorImpl(
```suggestion
class FavoriteInteratorImpl(
```

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/domain/model/PlaylistDto.kt
> +data class PlaylistDto(
Dto  – не domain слой

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/application/App.kt
> +        GlobalScope.launch {
Лучше не использовать Global Scope, на эту тему можно [почитать несколько советов](https://stackoverflow.com/a/54336168)

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/audioplayer/PlayerActivity.kt
> +class PlayerActivity : Fragment() {
Если это фрагмент, то всегда постфикс должен быть Fragment

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/audioplayer/PlayerActivity.kt
>      private lateinit var track: TrackDto
Зависимость ui от dto (что фактически data-слой)

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/audioplayer/PlayerActivity.kt
> +                Toast.makeText(requireContext(), "Добавлено в плейлист ${state.playlistName}", Toast.LENGTH_SHORT).show()
Лучше использовать string-res, иначе возникнут проблемы при локализации

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/audioplayer/PlayerActivity.kt
>          viewModel.releseMediaPlayer()
typo

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/audioplayer/bottom_sheet/PlaylistAdapter.kt
> +    var data = ArrayList<PlaylistDto>()
Это свойство доступно всем извне, нарушение принципа сокрытия данных

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/audioplayer/bottom_sheet/PlaylistViewHolder.kt
> +        val file = File(filePath, "${playlist.playlistName}.jpg")
Presentation слой работает напрямую с файлами (т. е. data)

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/audioplayer/view_model/PlayerViewModel.kt
> +        when(it){
Лучше отказаться от использования it для лучшей читаемости кода

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Favorite/FavoriteFragment.kt
>      private val tracksList = ArrayList<TrackDto>()
Фрагмент хранит данные для ui-представлений, он не должен быть ответственным за это

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/CreatePlaylist.kt
> +    private lateinit var textWatcher2: TextWatcher
Плохое название

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/CreatePlaylist.kt
> +    private var controlPlaylist: ControlPlaylist = ControlPlaylist()
Почему не при помощи di?

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/CreatePlaylist.kt
> +                        .setNeutralButton("Отмена") { dialog, which ->
Лучше sstring-res

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/CreatePlaylist.kt
> +                // empty
Можно воспользоваться функцией-расширением donOnTextChanged(), тогда не нужно будет переопределять лишние методы

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/CreatePlaylist.kt
> +                    Log.d("PhotoPicker", "No media selected")
Такие логи лучше убрать

На эту тему можно [посмотреть этот доклад](https://youtu.be/ydwuccVwYBM?si=pwgTEsqUG-G7Kcxm&t=513)

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/CreatePlaylist.kt
> +        var discribePlaylist: Int = 0
typo

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/CreatePlaylist.kt
> +                }
Кажется лишним

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/view_models/CreatePlaylistViewModel.kt
> +            val filePath = File(activity.getExternalFilesDir(Environment.DIRECTORY_PICTURES), "PlaylistMaker")
Явная работа с файлами в presentation-слое

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/view_models/CreatePlaylistViewModel.kt
> +    private val activity: FragmentActivity,
Никакой ссылки на активность не должно быть где-то снаружи
У ViewModel и Activity разные жизненный циклы

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/PlaylistAdapter.kt
> +    var data = ArrayList<PlaylistDto>()
Снаружи доступно изменение данных, что небезопасно

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/PlaylistViewHolder.kt
> +        val file = File(filePath, "${playlist.playlistName}.jpg")
Аналогично, работу с файлами нужно убрать из presentation

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/search/TracksSearchFragment.kt
>      private val tracksListHistory = ArrayList<TrackDto>()
Работа с данными для ui-представлений

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/res/layout/activity_player.xml
> +        android:id="@+id/standard_bottom_sheet"
`android:id="@+id/newPlaylist"`
Стоит унифицировать стиль именования идентификаторов

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/res/layout/fragment_newplaylist.xml
> +        android:id="@+id/textsBarrier4"
Странное наименование иддентификатора

2024-02-25 08:00 UTC, DmitrijEgorow commented on app/src/main/res/layout/playlist_item.xml
> +            android:text="1 трек"
Не стоит указывать явно текст
Если забыть его поменять явно (например, произошла ошибка при дозагрузке данных), то пользователь увидит "1 трек" (особенно странно это будет выглядеть, если приложение переведено на другой язык)
Если хочется посмотреть, как это будет выглядеть в дизайне, то можно использовать namespace tools:
`tools:text=""`

2024-02-25 08:07 UTC, DmitrijEgorow commented
- [ ] Вновь созданный плейлист не появляется в списке
- [ ] Лучше не давать пользователю вводить несколько строчек в editText с заголовком (там сейчас показывается кнопка переноса строки)
- [ ] Название и Описание тоже должны иметь синий цвет

https://github.com/klyakssa/PlaylistNew/assets/36837067/f88f2bdd-af44-4cfb-82fb-e51894c25834

2024-02-25 08:08 UTC, DmitrijEgorow commented
Плейсхолдер не нужно обрезать по вертикали

![Screenshot_20240225_082706](https://github.com/klyakssa/PlaylistNew/assets/36837067/52369cad-c5ea-4596-ba6e-bc94e9ef8df2)

2024-02-25 08:09 UTC, DmitrijEgorow commented
- [ ] Цвет курсора не должен быть зелёным
- [ ] Крестик имеет странную серую обводку

![Screenshot_20240225_082828](https://github.com/klyakssa/PlaylistNew/assets/36837067/b9214d7d-90e2-408e-a099-ca115aa4dcf4)

2024-02-25 08:13 UTC, DmitrijEgorow commented
- [ ] При возврате назад на экран со списком элементы становятся некликабельными, заново перейти на аудиоплеер не получится
- [ ] Нижнее меню навигации не должно быть показано на экране аудиоплеера

https://github.com/klyakssa/PlaylistNew/assets/36837067/de0bdc22-c1b5-4bee-bf9d-bef745ad5e15

2024-02-25 08:14 UTC, DmitrijEgorow commented
- [ ] Нижнее меню навигации нужно убрать
- [ ] Синяя окантовка у editText

![Screenshot_20240225_083412](https://github.com/klyakssa/PlaylistNew/assets/36837067/aeb0c93f-9f78-487c-af8a-ff4fc5cb5ef8)

2024-02-25 08:15 UTC, DmitrijEgorow commented
- [ ] Зеленый цвет у switch не входит в цветовую палитру приложения
- [ ] Switch справа имеет маленький отступ от края экрана

![Screenshot_20240225_083532](https://github.com/klyakssa/PlaylistNew/assets/36837067/78636edf-5f90-4118-86fc-c92e05169e9a)

2024-02-25 08:17 UTC, DmitrijEgorow commented
- [ ] Нет закруглений у обложки

![Screenshot_20240225_083717](https://github.com/klyakssa/PlaylistNew/assets/36837067/0ce13af5-db9f-4ca2-aeb4-7754bf8d2dee)

2024-02-25 08:20 UTC, DmitrijEgorow commented
Панель нижней навигации перестаёт отображаться при возврате назад с экрана создания плейлиста

https://github.com/klyakssa/PlaylistNew/assets/36837067/11c56991-0795-4466-a641-2d5bc6d5f672

2024-02-25 08:22 UTC, DmitrijEgorow commented
Приложение аварийно завершается при открытии в режиме плавающего / разделённого окна, либо unfold
Нужно аккуратно поработать с методами ЖЦ активности и фрагмента


https://github.com/klyakssa/PlaylistNew/assets/36837067/89c80ffd-daeb-4f4f-97a4-56017a520998


```
FATAL EXCEPTION: main  
Process: com.kuzmin.playlist, PID: 15000  
java.lang.RuntimeException: Unable to pause activity {com.kuzmin.playlist/com.kuzmin.playlist.presentation.main.RootActivity}: java.lang.IllegalStateException  
at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5557)  
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5508)  
at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6312)  
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6212)  
at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)  
at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)  
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)  
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)  
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)  
at android.os.Handler.dispatchMessage(Handler.java:106)  
at android.os.Looper.loopOnce(Looper.java:226)  
at android.os.Looper.loop(Looper.java:313)  
at android.app.ActivityThread.main(ActivityThread.java:8663)  
at java.lang.reflect.Method.invoke(Native Method)  
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)  
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)  
Caused by: java.lang.IllegalStateException  
at android.media.MediaPlayer._pause(Native Method)  
at android.media.MediaPlayer.pause(MediaPlayer.java:1546)  
at com.kuzmin.playlist.data.repository.MediaPlayer.MediaPlayerRepositoryImpl.pauseMediaPlayer(MediaPlayerRepositoryImpl.kt:91)  
at com.kuzmin.playlist.domain.mediaplayer.impl.MediaPlayerInteractionImpl.pauseMediaPlayer(MediaPlayerInteractionImpl.kt:25)  
at com.kuzmin.playlist.presentation.audioplayer.view_model.PlayerViewModel.pauseMediaPlayer(PlayerViewModel.kt:115)  
at com.kuzmin.playlist.presentation.audioplayer.PlayerActivity.onPause(PlayerActivity.kt:221)  
at androidx.fragment.app.Fragment.performPause(Fragment.java:3325)  
at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:672)  
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:304)  
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)  
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)  
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)  
at androidx.fragment.app.FragmentManager.dispatchPause(FragmentManager.java:2970)  
at androidx.fragment.app.Fragment.performPause(Fragment.java:3318)  
at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:672)  
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:304)  
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)  
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)  
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)  
at androidx.fragment.app.FragmentManager.dispatchPause(FragmentManager.java:2970)  
at androidx.fragment.app.FragmentController.dispatchPause(FragmentController.java:296)  
at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:284)  
at android.app.Activity.performPause(Activity.java:8485)  
at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1530)
```

2024-02-25 08:36 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/data/db/dao/PlaylistDao.kt
> +    suspend fun getPlaylists(): List<PlaylistEntity>
Room позволяет возвращать сразу `Flow<List<PlaylistEntity>>`

2024-02-26 14:41 UTC, klyakssa commented on app/src/main/java/com/kuzmin/playlist/di/ViewModelModule.kt
> +        PlaylistViewModel(get())
UpdatePlaylist это интерфейс, PlaylistViewModel его реализует

2024-02-28 18:19 UTC, DmitrijEgorow requested changes

2024-02-28 18:19 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/CreatePlaylist.kt
> +        binding.back.setOnClickListener {
Закрытие экрана «Создание плейлиста» происходит при нажатии навигационной кнопки «Назад», системной кнопки Back или при выполнении соответствующего жеста
Показывать подтверждающий диалог нужно при любом варианте

2024-02-28 18:19 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/application/App.kt
> +        runBlocking {
У меня при холодном старте приложения просто чёрный экран

2024-02-28 19:42 UTC, klyakssa commented on app/src/main/java/com/kuzmin/playlist/presentation/application/App.kt
> +        runBlocking {
У меня всё работает на телефоне физическом

2024-02-28 23:39 UTC, klyakssa commented
![photo_1_2024-02-29_02-38-53](https://github.com/klyakssa/PlaylistNew/assets/134778434/4e595b37-8149-4cbe-9533-f561a76e8936)
![photo_2_2024-02-29_02-38-53](https://github.com/klyakssa/PlaylistNew/assets/134778434/0f45da4a-dde7-43d6-92f6-9fd02f0d5726)

2024-02-28 23:40 UTC, klyakssa commented
![image](https://github.com/klyakssa/PlaylistNew/assets/134778434/5fdebe9b-c806-471e-8d61-e45da0e4fa6e)
Это уже на эмуляторе

2024-04-03 10:12 UTC, closed without merging