Sprint 22
klyakssa/PlaylistNew pull request #29
Opened 2024-04-03 10:16 UTC by klyakssa

2024-04-04 19:45 UTC, DmitrijEgorow requested changes

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/build.gradle
> +    implementation 'com.markodevcic:peko:3.0.4'
Зачем библиотека?

Зачем у пользователя запрашивать разрешения на доступ к файлам, если используется photo picker?


https://github.com/klyakssa/PlaylistNew/assets/36837067/eb3963e7-a057-4b49-a095-bd7faf3bc5ef

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/data/repository/PlaylistRepository/PlaylistRepositoryImpl.kt
> +    private val context2: Context,
Плохое название поля

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/domain/db/impl/FavoriteIteratorImpl.kt
> +class FavoriteIteratorImpl(
```suggestion
class FavoriteInteratorImpl(
```

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/domain/db/impl/PlaylistIteratorImpl.kt
> +import android.content.Context
domain слой должен быть свободен от классов Android

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/domain/db/impl/PlaylistIteratorImpl.kt
> +    private val listener: ArrayList<PlaylistIterator.PlaylistListener> = ArrayList()
1. Лучше использовать абстракции, а не конкретные реализации
2. Очень странно, что под термином <один> listener скрывается массив

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/domain/db/iterators/PlaylistIterator.kt
> +import android.content.Context
Аналогично

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/application/App.kt
> +
Code -> Reformat Code

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/audioplayer/PlayerFragment.kt
> +class PlayerFragment : Fragment(), OnBackButtonListener{
Нарушение принципа единственности ответственности

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/audioplayer/PlayerFragment.kt
> +        const val TRACK_TO_ARRIVE = "track"
companion object обычно идёт в конце класса

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/audioplayer/PlayerFragment.kt
> +                    "Трек уже добавлен в плейлист ${state.playlistName}",
лучше в string-res

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/audioplayer/bottom_sheet/PlaylistViewHolder.kt
> +        artistName.text = playlist.countTracks.toString() + " треков"
аналогично

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/audioplayer/view_model/PlayerViewModel.kt
> +        //initUpdate()
не стоит вливать закомментированный код в master

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/CreatePlaylist.kt
> +    private lateinit var textWatcher2: TextWatcher
нехорошее название поля

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/CreatePlaylist.kt
> +    private var fromWho: Int = 0
сразу сложно понять, что это означает и почему Int

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/CreatePlaylist.kt
> +    private val onBackPlaylistDebounce: (RootActivity) -> Unit = debounce<RootActivity>(CLICK_DEBOUNCE_DELAY, GlobalScope, Dispatchers.Main) { activity ->
Лучше не использовать GlobalScope

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/CreatePlaylist.kt
> +                        .setNeutralButton("Отмена") { dialog, which ->
string-res

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/models/CreatePlaylistState.kt
> +        val playlistName: String
Это хорошо

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/PlaylistAdapter.kt
> +    var data = ArrayList<Playlist>()
почему public?

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/PlaylistFragment.kt
> +            findNavController().navigate(R.id.action_libraryFragment_to_addPlaylist, bundleOf("from" to 2))
магические числа

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/res/layout/activity_settings.xml
>              android:id="@+id/switch1"
плохое название идентификатора

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/application/App.kt
> +        GlobalScope.launch {
Лучше не использовать GlobalScope

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/search/view_model/TracksSearchViewModel.kt
Студия подсказывает: This field leaks a context object

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/search/view_model/TracksSearchViewModel.kt
>              )
Reformat Code

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/CreatePlaylist.kt
> +class CreatePlaylist: Fragment(), OnBackButtonListener{
Если это фрагмент, то должен обязательно присутствовать постфикс Fragment

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/AddNewPlaylist/view_models/CreatePlaylistViewModel.kt
> +package com.kuzmin.playlist.presentation.library.Fragments.Playlist.AddNewPlaylist.view_models
названия пакетов не принято писать с большой буквы

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/domain/db/impl/PlaylistIteratorImpl.kt
> +import kotlinx.coroutines.delay
Стоит почистить импорты

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/search/TracksSearchFragment.kt
Почему ActivitySearchBinding во фрагменте?

2024-04-04 19:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/search/TracksSearchFragment.kt
>      private val tracksAdapter = TracksListAdapter{_,it ->
Reformat Code

2024-04-04 19:46 UTC, DmitrijEgorow commented
CardView плейлистов должны быть квадратными, иметь закругления со всех четырех краев

https://github.com/klyakssa/PlaylistNew/assets/36837067/180cd812-5b86-4b58-bff5-59cc64c336e1

2024-04-04 19:47 UTC, DmitrijEgorow commented
У всех плейлистов стала отображаться одна и та же картинка

https://github.com/klyakssa/PlaylistNew/assets/36837067/8442ee57-da2f-4a49-8cc9-1cca9cad648d

2024-04-04 19:48 UTC, DmitrijEgorow commented
Если на телефоне нет Интернета, то заглушка не показывается


https://github.com/klyakssa/PlaylistNew/assets/36837067/56400c52-a170-4d4c-a7d5-3c0364e5b63c

2024-04-04 19:49 UTC, DmitrijEgorow commented
Сливается с фоном

https://github.com/klyakssa/PlaylistNew/assets/36837067/3ddb8f5c-123a-48a1-bcf9-5786f14bf97a

2024-04-04 19:49 UTC, DmitrijEgorow commented
![Screenshot_20240404_215812](https://github.com/klyakssa/PlaylistNew/assets/36837067/5951caf5-48df-4e29-8c07-b62de19e77d2)

- [ ] Вроде хватает места, чтобы написать слово полностью
- [ ] Точка в конце не нужна

2024-04-04 19:51 UTC, DmitrijEgorow commented
Нижнее меню навигации не нужно на экране плеера и при создании нового плейлиста

https://github.com/klyakssa/PlaylistNew/assets/36837067/0d4ee43a-5f05-40c3-b8de-c4a70b2f2e1c

2024-04-04 19:51 UTC, DmitrijEgorow commented
Некорретное название композиции


https://github.com/klyakssa/PlaylistNew/assets/36837067/1e2450f0-a43e-4d62-81ae-759dec47f663

2024-04-04 20:33 UTC, DmitrijEgorow commented
При возврате назад с экрана плеера композиция продолжает играть, это нужно исправить

https://github.com/klyakssa/PlaylistNew/assets/36837067/580202a9-6898-4f36-aaa9-7ce0d959facb

2024-04-05 22:25 UTC, klyakssa commented
![image](https://github.com/klyakssa/PlaylistNew/assets/134778434/be622c15-dfeb-444a-a9ee-b89347af0
У нас интерфейсы хранятся в domain, а реализации этих интерфейсов хранятся в data, по любому будет и в domain и в data, использоваться классы Dto и классы которые используются только в domain и presentation

2024-04-10 20:25 UTC, DmitrijEgorow commented
Появляется нижнее меню

https://github.com/klyakssa/PlaylistNew/assets/36837067/a0a2bd01-c895-4d53-9c39-8d38d4e1e824

2024-04-10 20:26 UTC, DmitrijEgorow commented
> ![image](https://private-user-images.githubusercontent.com/134778434/320152631-dcaa4bdd-f42a-40c9-bb85-d733e4953e2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3ODA5NDQsIm5iZiI6MTcxMjc4MDY0NCwicGF0aCI6Ii8xMzQ3Nzg0MzQvMzIwMTUyNjMxLWRjYWE0YmRkLWY0MmEtNDBjOS1iYjg1LWQ3MzNlNDk1M2UyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQyMDI0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTk2MWE4ZDM0YmYzZWU2MjAzNjkxYjhlZTEwY2Q1MjY4MzFlNTY2MmVmODEzNTM2ZDcxN2I3NmE5MGY0YmExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cX88NPbY8bCiCeZUDNUh1JnvibhorZRNcPTFx-92dDc)
> 
> У нас интерфейсы хранятся в domain, а реализации этих интерфейсов хранятся в data, по любому будет и в domain и в data, использоваться классы Dto и классы которые используются только в domain и presentation

Для этого есть mappers

2024-04-10 20:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/domain/db/impl/PlaylistIteratorImpl.kt
> +        context: Context
Зачем контекст?

2024-04-10 20:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/main/RootActivity.kt
> +//                when (state) {
Не стоит вливать закомментированный код в мастер

2024-04-10 20:45 UTC, DmitrijEgorow commented on app/src/main/java/com/kuzmin/playlist/presentation/library/Fragments/Playlist/view_models/PlaylistViewModel.kt
> +        }else{
Стоит отформатировать код

2024-04-10 20:52 UTC, DmitrijEgorow commented
Крит: история поиска

https://github.com/klyakssa/PlaylistNew/assets/36837067/27c15303-aa1b-4a91-80de-4ed76a90dce9

2024-04-10 23:05 UTC, klyakssa commented on app/src/main/java/com/kuzmin/playlist/domain/db/impl/PlaylistIteratorImpl.kt
> +        context: Context
Для того что бы в дальнейшем получить доступ к сохранению картинки

2024-04-13 14:32 UTC, klyakssa commented on app/src/main/java/com/kuzmin/playlist/domain/db/impl/PlaylistIteratorImpl.kt
> +        context: Context
Пытался через koin но он выдает ошибку что, в классе context "contentResolver" равен null, пришлось передать context по функциям, причем работала всё нормально на обычном телефоне, это только на эмуляторя так он пишет.

2024-04-13 14:57 UTC, klyakssa commented
![image](https://github.com/klyakssa/PlaylistNew/assets/134778434/00321a21-ee47-4791-b2b5-a1ad38ca508b)
Если вы имеет ввиду context который передается в конструктор viewmodel, то это context не из фрагмента, а из koin, а koin уже берет этот контекст во время создания класса App.

2024-04-13 14:57 UTC, klyakssa commented on app/src/main/java/com/kuzmin/playlist/domain/db/impl/PlaylistIteratorImpl.kt
> +        context: Context
Я разобрался исправил

2024-04-14 23:06 UTC, merged